name: 'yudai_v2'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'yudai_v2'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  yudai_v2:
    # Config indicated by + and applies to all files under models/example/
    generated:
      +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table

# Configuring snapshots
snapshots:
  yudai_v2:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Configuring seeds
seeds:
  yudai_v2:
    +schema: raw_data 