yudai_v2:
  outputs:
    dev:
      type: duckdb
      path: '{{ env_var("DBT_DUCKDB_PATH", "~/yudai/data/yudai_v2.duckdb") }}'
      schema: main
      threads: 4
      keepalives_idle: 0
      search_path: main
    prod:
      type: duckdb
      path: '{{ env_var("DBT_DUCKDB_PATH", "~/yudai/data/yudai_v2.duckdb") }}'
      schema: main
      threads: 4
      keepalives_idle: 0
      search_path: main
  target: dev 